import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Link from "next/link";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        
        <header>
            {/* Tittle */}
            <h1>
                <a href="/">Alejandro Zerpa<b><span id='point'>.</span></b></a>
            </h1>

            {/* Nav */}
            <nav>
                <ul>
                    <Link id='link' href='/'>HOME</Link>
                    <Link id='link' href='/about'>ABOUT</Link>
                    <Link id='link' href='/contact'>CONTACT</Link>
                </ul>
            </nav>

        </header>

        {children}

        <footer>
            <p>© 2021 Alejandro Zerpa. All rights reserved.</p>
        </footer>
    
      </body>
    </html>
  );
}
